services:
  hobby:
    build:
      context: ./../docker
      dockerfile: Dockerfile
    container_name: hobby
    hostname: hobby
    restart: always
    networks:
      - hwnet
    ports:
      - ${HTTP_PORT}:80
      - ${HTTPS_PORT}:443
    volumes:
      - './../:/var/www/html'
    environment:
      XDEBUG_CONFIG: client_host=${HOST_INTERNAL}
      XDEBUG_REMOTE_CONNECT_BACK: 1
      PHP_IDE_CONFIG: "serverName=hobby.huancosoft.com"
networks:
    hwnet:
